version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "infra"
    reviewers:
      - viper0179
    commit-message:
      prefix: "ci"

  - package-ecosystem: nuget
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
    labels:
      - "infra"
    reviewers:
      - viper0179
    commit-message:
      prefix: nuget
    groups:
      Avalonia:
        patterns:
          - "*Avalonia*"
      Microsoft:
        patterns:
          - "Microsoft*"
      Silk.NET:
        patterns:
          - "Silk.NET*"
      OpenTK:
        patterns:
          - "OpenTK*"
      NUnit:
        patterns:
          - "NUnit*"
