name: Prepare Version
description: Identifies the version number being compiled.

inputs:
  explicit_version:
    description: "The explicit version use (if defined)."
    required: false

outputs:
  version_number:
    description: "The version number used."
    value: ""
  version_suffix:
    description: "The hash identifier of the commit."
    value: ""
    
runs:
  using: "composite"
  steps:
    - id: get_git_hash
      name: Get Git hash
      run: echo "short_hash=$(git rev-parse --short "${{ github.sha }}")" >> $GITHUB_OUTPUT
      shell: bash

    - id: bump_preview_version
      name: Bump preview version
      if: inputs.explicit_version == ''
      uses: vers-one/dotnet-project-version-updater@v1.7
      with:
        file: "src/.build/common.props"
        version: bump-minor
        
    - name: Set preview version
      if: inputs.explicit_version == ''
      shell: bash
      run: |
        echo "version_number=${{ steps.bump_preview_version.outputs.newVersion }}" >> $GITHUB_OUTPUT
        echo "version_suffix=preview.${{ github.run_number }}+${{ steps.get_git_hash.outputs.short_hash }}" >> $GITHUB_OUTPUT

    - id: update_version
      name: Update version
      if: inputs.explicit_version != ''
      uses: vers-one/dotnet-project-version-updater@v1.7
      with:
        file: "src/.build/common.props"
        version: ${{ inputs.explicit_version }}
        
    - name: Set release version
      if: inputs.explicit_version != ''
      shell: bash
      run: |
        echo "version_number=${{ inputs.explicit_version }}" >> $GITHUB_OUTPUT