blank_issues_enabled: true
contact_links:
  - name: Latte Softworks Discord
    url: https://latte.to/discord
    about: This is the home of development for the ryujinx-mirror fork, feel free to make a post in `#ryujinx-help` for general support & technical issues
