name: Bump Version
description: Bumps the version to the specified value.

inputs:
  target_file:
    description: "The name of the file to update."
    required: true
  new_version:
    description: "The new version to use."
    required: true
  token:
    description: "The GitHub token to use."
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Set branch name
      id: set-branch-name
      shell: bash
      run: |
        BRANCH_NAME="bump-version-${{ inputs.new_version }}"
        echo "result=$BRANCH_NAME" >> $GITHUB_OUTPUT
        
    - name: Set up Git config
      shell: bash
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Create branch
      shell: bash
      run: |
        git checkout -b "${{ steps.set-branch-name.outputs.result }}"
        
    - name: Update version
      uses: vers-one/dotnet-project-version-updater@v1.7
      with:
        file: ${{ inputs.target_file }}
        version: ${{ inputs.new_version }}

    - name: Commit changes
      shell: bash
      run: |
        git commit -am "Bumping version to ${{ inputs.new_version }}"
        git push origin "${{ steps.set-branch-name.outputs.result }}"

    - name: Create pull request
      uses: gr2m/create-or-update-pull-request-action@v1
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        title: "Bump version to ${{ inputs.new_version }}"
        body: "This PR was automatically generated to bump the version in `${{ inputs.target_file }}` to `${{ inputs.new_version }}`."
        branch: ${{ steps.set-branch-name.outputs.result }}
        path: .
