name: Package
description: Packages the application

inputs:
  package_dir:
    description: "The location where the package is located."
    required: true
  version:
    description: "The version of the package."
    required: true
  zip_os_name:
    description: "The target file name for the host operating system."
    required: true

runs:
  using: "composite"
  steps:
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "hyjinx-${{ inputs.version }}-${{ inputs.zip_os_name }}"
        path: ${{ inputs.package_dir }}