name: Package
description: Packages the application

inputs:
  packager:
    description: "The target operating system. (windows, linux, macos)"
    required: true
  staging_dir:
    description: "The location where the package is located."
    required: true
  version:
    description: "The version of the package."
    required: true

runs:
  using: "composite"
  steps:
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "hyjinx-${{ inputs.version }}-${{ inputs.packager }}"
        path: ${{ inputs.staging_dir }}