name: Package
description: Packages the application

inputs:
  runtime_identifier:
    description: "The runtime identifier."
    required: true
  package_suffix:
    description: "The package suffix (typically the OS identifier)."
    required: true
  packager:
    description: "The target operating system. (windows, linux, macos)"
    required: true
  staging_dir:
    description: "The location where the package contents is located."
    required: true
  version:
    description: "The version of the package."
    required: true
  package_dir:
    description: "The location where the packages will be placed."
    required: true    

runs:
  using: "composite"
  steps:
    - name: Create output directory
      shell: bash
      run: mkdir "${{ inputs.package_dir }}"
        
    - name: Package for Windows (Portable)
      if: inputs.packager == 'windows'
      shell: bash
      run: |
        cp -a distribution/windows/. "${{ inputs.staging_dir }}/"
        cp -a distribution/misc/Logo.png "${{ inputs.staging_dir }}/"
        cp -a distribution/legal/. "${{ inputs.staging_dir }}/"
        
        pushd "${{ inputs.staging_dir }}"
        7z a "../${{ inputs.package_dir }}/hyjinx-${{ inputs.version }}-${{ inputs.package_suffix }}.zip" .
        popd
        
    - name: Package for Linux (Portable)
      if: inputs.packager == 'linux'
      shell: bash
      run: |
        cp -a distribution/linux/portable/. "${{ inputs.staging_dir }}/"
        cp -a distribution/misc/Logo.png "${{ inputs.staging_dir }}/"
        cp -a distribution/legal/. "${{ inputs.staging_dir }}/"
        
        pushd "${{ inputs.staging_dir }}"
        tar -czvf "../${{ inputs.package_dir }}/hyjinx-${{ inputs.version }}-${{ inputs.package_suffix }}.tar.gz" .
        popd
