<Project>
  
  <ItemGroup Condition=" '$(IsLegacyEnabled)' != 'true' ">
    <!-- Remove all code within legacy folders. -->
    <Compile Update="**/Legacy/**/*.cs" Visible="false" />
    <!-- Remove all code denoted as legacy files. -->
    <Compile Update="**/*.Legacy.cs" Visible="false" />
  </ItemGroup>
  
</Project>