<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\RTCV\Source\Frontend\StandaloneRTC\StandaloneRTC.csproj" />
    <ProjectReference Include="..\..\RTCV\Source\Frontend\UI\UI.csproj" />
    <ProjectReference Include="..\..\RTCV\Source\Libraries\Common\Common.csproj" />
    <ProjectReference Include="..\..\RTCV\Source\Libraries\CorruptCore\CorruptCore.csproj" />
    <ProjectReference Include="..\..\RTCV\Source\Libraries\NetCore\NetCore.csproj" />
    <ProjectReference Include="..\..\RTCV\Source\Libraries\Vanguard\Vanguard.csproj" />
    <ProjectReference Include="..\..\RTCV\Source\Libraries\ZombieCeras\src\Ceras\Ceras.csproj" />
    <ProjectReference Include="..\src\Hyjinx.Memory\Hyjinx.Memory.csproj" />
  </ItemGroup>

</Project>
