name: build

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  checks: write

env:
  POWERSHELL_TELEMETRY_OPTOUT: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  
jobs:
  build:
    name: ${{ matrix.platform.name }} (${{ matrix.configuration }})
    runs-on: ${{ matrix.platform.runner }}-latest
    timeout-minutes: 60
    
    strategy:
      matrix:
        configuration: [ Release ]
        platform:
          - { name: win-x64,    runner: windows,  zip_os_name: win_x64    }
          - { name: linux-x64,  runner: ubuntu,   zip_os_name: linux_x64  }
      fail-fast: false
      
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v6
        with:
          global-json-file: global.json

      - name: Determine git hash
        id: git_short_hash
        run: echo "result=$(git rev-parse --short "${{ github.sha }}")" >> $GITHUB_OUTPUT
        shell: bash
                          
      - name: Build
        run: dotnet build -c "${{ matrix.configuration }}" --version-suffix "${{ steps.git_short_hash.outputs.result }}" -p:DebugType=portable

      - name: Run tests
        run: dotnet test --no-build -c "${{ matrix.configuration }}" --collect:"XPlat Code Coverage" --results-directory TestResults
        timeout-minutes: 30

      - name: Upload test results
        uses: actions/upload-artifact@v7
        with:
          name: coverage-${{ matrix.platform.name }}-${{ matrix.configuration }}
          path: TestResults/**/*
          if-no-files-found: error

      - name: Upload coverage report
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1.3.0
        env:
          CODACY_REPORTER_OPTIONS: --prefix ${{ github.workspace }}
        with:
          project-token: ${{ secrets.CODACY_TOKEN }}
          coverage-reports: TestResults/**/coverage.cobertura.xml
