name: labeler

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/labeler.yml'
      - '.github/workflows/labeler.yml'

permissions:
  contents: read
  pull-requests: write
  
jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
           # Ensure we pin the source origin as pull_request_target run under forks.
           fetch-depth: 0
           repository: hyjinx-emu/hyjinx
           ref: main

      - name: Apply labels
        uses: actions/labeler@v5