name: triage

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/labeler.yml'
      - '.github/workflows/triage.yml'

permissions:
  contents: read
  pull-requests: write
  
jobs:
  triage:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch labeler.yml
        uses: actions/checkout@v4
        with:
           # Ensure we pin the source origin as pull_request_target run under forks.
           fetch-depth: 0
           repository: hyjinx-emu/hyjinx
           ref: main

      - name: Update labels based on changes in PR
        id: apply_labels
        uses: actions/labeler@v5
        with:
          sync-labels: true
          dot: true

      - name: Output new labels
        if: always()
        run: |
          echo "${{ steps.apply_labels.outputs.new-labels }}"